### ISSUE TITLE
Button ON (status projects)

### ISSUE THREAD

**Issue by abipit** [francescou/docker-compose-ui#67] opened 2016-11-16 09:39 UTC
Hi @francescou, 

really really cool your docker-compose-ui, thank you !

I have a problem with the ON button for new project. With yours demos projects, no problem. But when a create a project and "UP" it, the status don't become "ON". For example, as you can see below, with my test project ASSE, whereas containers are up and website accessible, it's not "ON".
Can you explain me why ? I don't find.

For hello-node project, just after the click on "UP" button, the status is "ON".

As you can see, I had a button OFF but I made this modification after my tests.

<img width="1232" alt="capture d ecran 2016-11-16 a 10 27 24" src="https://cloud.githubusercontent.com/assets/16560507/20341785/f4cb5942-abe7-11e6-9e75-25da1bed3d40.png">

Thank you for your back.

**Comment by allamand** [comment] 2016-11-16 16:39
Hi @abipit didn't have this in my tests. do you have logs from compose-ui ?

**Comment by abipit** [comment] 2016-11-16 16:54
Hi @allamand, thank you for your response.

Nothing special in the log. The trace below start when I click on the button "UP". The containers and website are UP. But the button not ON :(
If I click on DOWN button, it's ok, the containers are destroy.
I don't understand the difference between my project and the demo project.

Do you have an idea with the log ?

`DEBUG:root:get project /opt/docker-compose-projects/Azerty PL
DEBUG:compose.config.config:Using configuration files: /opt/docker-compose-projects/Azerty PL/docker-compose.yml
DEBUG:docker.auth.auth:Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
DEBUG:docker.auth.auth:No config file found
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/info HTTP/1.1" 200 1310
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/json?all=0&limit=-1&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3DAzertypremierleague%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&size=0 HTTP/1.1" 200 3
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/json?all=1&limit=-1&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3DAzertypremierleague%22%2C+%22com.docker.compose.service%3Ddb%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&size=0 HTTP/1.1" 200 3
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/json?all=1&limit=-1&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3DAzertypremierleague%22%2C+%22com.docker.compose.service%3Dphpmyadmin%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&size=0 HTTP/1.1" 200 3
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/json?all=1&limit=-1&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3DAzertypremierleague%22%2C+%22com.docker.compose.service%3Dwordpress%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&size=0 HTTP/1.1" 200 3
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/images/mysql/json HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/images/phpmyadmin/phpmyadmin/json HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/images/ith/wpfront/json HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/json?all=1&limit=-1&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3DAzertypremierleague%22%2C+%22com.docker.compose.service%3Ddb%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&size=0 HTTP/1.1" 200 3
DEBUG:compose.project:phpmyadmin has upstream changes (db)
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/json?all=1&limit=-1&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3DAzertypremierleague%22%2C+%22com.docker.compose.service%3Dphpmyadmin%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&size=0 HTTP/1.1" 200 3
DEBUG:compose.project:wordpress has upstream changes (db)
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/json?all=1&limit=-1&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3DAzertypremierleague%22%2C+%22com.docker.compose.service%3Dwordpress%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&size=0 HTTP/1.1" 200 3
DEBUG:compose.parallel:Pending: set([<Service: wordpress>, <Service: phpmyadmin>, <Service: db>])
DEBUG:compose.parallel:Starting producer thread for <Service: db>
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/images/mysql/json HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/json?all=1&limit=-1&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3DAzertypremierleague%22%2C+%22com.docker.compose.service%3Ddb%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&size=0 HTTP/1.1" 200 3
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/images/mysql/json HTTP/1.1" 200 None
DEBUG:compose.service:Added config hash: c43af1d097010955a67accfed50b15300e987bd343f1e1cabc3c9991a0408d86
INFO:compose.service:Creating kplhfdb
DEBUG:requests.packages.urllib3.connectionpool:"POST /v1.21/containers/create?name=kplhfdb HTTP/1.1" 201 90
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/5da35c64b70c0b2005b959edc8040003a1b50c55ed99ac6e1ef19db6b5cbe277/json HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"POST /v1.21/containers/5da35c64b70c0b2005b959edc8040003a1b50c55ed99ac6e1ef19db6b5cbe277/attach?stderr=1&logs=0&stream=1&stdout=1 HTTP/1.1" 101 0
DEBUG:compose.parallel:Pending: set([<Service: wordpress>, <Service: phpmyadmin>])
DEBUG:compose.parallel:Pending: set([<Service: wordpress>, <Service: phpmyadmin>])
DEBUG:compose.parallel:Pending: set([<Service: wordpress>, <Service: phpmyadmin>])
DEBUG:requests.packages.urllib3.connectionpool:"POST /v1.21/containers/5da35c64b70c0b2005b959edc8040003a1b50c55ed99ac6e1ef19db6b5cbe277/start HTTP/1.1" 204 0
DEBUG:compose.parallel:Finished processing: <Service: db>
DEBUG:compose.parallel:Pending: set([<Service: wordpress>, <Service: phpmyadmin>])
DEBUG:compose.parallel:Starting producer thread for <Service: wordpress>
DEBUG:compose.parallel:Starting producer thread for <Service: phpmyadmin>
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/images/phpmyadmin/phpmyadmin/json HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/images/ith/wpfront/json HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/json?all=1&limit=-1&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3DAzertypremierleague%22%2C+%22com.docker.compose.service%3Dphpmyadmin%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&size=0 HTTP/1.1" 200 3
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/json?all=1&limit=-1&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3DAzertypremierleague%22%2C+%22com.docker.compose.service%3Dwordpress%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&size=0 HTTP/1.1" 200 3
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/images/phpmyadmin/phpmyadmin/json HTTP/1.1" 200 None
DEBUG:compose.service:Added config hash: 277d0425f8013f8663617d22e07e03d4f9f1dd44b08f8780ac65307f4cee86e8
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/images/ith/wpfront/json HTTP/1.1" 200 None
DEBUG:compose.service:Added config hash: 672ef8ce3d010ca8a1137211a77e91edc854fce0fc1bd560d1ffbf5e00cc6ea1
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/json?all=0&limit=-1&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3DAzertypremierleague%22%2C+%22com.docker.compose.service%3Ddb%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&size=0 HTTP/1.1" 200 1513
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/json?all=0&limit=-1&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3DAzertypremierleague%22%2C+%22com.docker.compose.service%3Ddb%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&size=0 HTTP/1.1" 200 1513
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/5da35c64b70c0b2005b959edc8040003a1b50c55ed99ac6e1ef19db6b5cbe277/json HTTP/1.1" 200 None
INFO:compose.service:Creating kplhfmy
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/5da35c64b70c0b2005b959edc8040003a1b50c55ed99ac6e1ef19db6b5cbe277/json HTTP/1.1" 200 None
INFO:compose.service:Creating kplhfwp
DEBUG:compose.parallel:Pending: set([])
DEBUG:requests.packages.urllib3.connectionpool:"POST /v1.21/containers/create?name=kplhfmy HTTP/1.1" 201 90
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/98e7f6e5d70b546ac73f4ce1c06a6247512d6c6759ac8276a0a3a6d6b8f80c1d/json HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"POST /v1.21/containers/98e7f6e5d70b546ac73f4ce1c06a6247512d6c6759ac8276a0a3a6d6b8f80c1d/attach?stderr=1&logs=0&stream=1&stdout=1 HTTP/1.1" 101 0
DEBUG:requests.packages.urllib3.connectionpool:"POST /v1.21/containers/create?name=kplhfwp HTTP/1.1" 201 90
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/3e66c25378e40824577bb2193772520c75d3c1ee54a5b72b9e44ca3ab8de284a/json HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"POST /v1.21/containers/3e66c25378e40824577bb2193772520c75d3c1ee54a5b72b9e44ca3ab8de284a/attach?stderr=1&logs=0&stream=1&stdout=1 HTTP/1.1" 101 0
DEBUG:compose.parallel:Pending: set([])
DEBUG:compose.parallel:Pending: set([])
DEBUG:compose.parallel:Pending: set([])
DEBUG:compose.parallel:Pending: set([])
DEBUG:compose.parallel:Pending: set([])
DEBUG:requests.packages.urllib3.connectionpool:"POST /v1.21/containers/98e7f6e5d70b546ac73f4ce1c06a6247512d6c6759ac8276a0a3a6d6b8f80c1d/start HTTP/1.1" 204 0
DEBUG:compose.parallel:Finished processing: <Service: phpmyadmin>
DEBUG:compose.parallel:Pending: set([])
DEBUG:compose.parallel:Pending: set([])
DEBUG:compose.parallel:Pending: set([])
DEBUG:requests.packages.urllib3.connectionpool:"POST /v1.21/containers/3e66c25378e40824577bb2193772520c75d3c1ee54a5b72b9e44ca3ab8de284a/start HTTP/1.1" 204 0
DEBUG:compose.parallel:Finished processing: <Service: wordpress>
DEBUG:compose.parallel:Pending: set([])
INFO:werkzeug:172.17.0.2 - - [16/Nov/2016 16:44:39] "POST /api/v1/projects HTTP/1.1" 200 -
DEBUG:root:get project /opt/docker-compose-projects/Azerty PL
DEBUG:compose.config.config:Using configuration files: /opt/docker-compose-projects/Azerty PL/docker-compose.yml
DEBUG:root:{'Azerty PL': '/opt/docker-compose-projects/Azerty PL', 'ASEC': '/opt/docker-compose-projects/ASEC', 'SFC': '/opt/docker-compose-projects/SFC', 'AS SE': '/opt/docker-compose-projects/AS SE', 'hello-node': '/opt/docker-compose-projects/hello-node'}
DEBUG:docker.auth.auth:Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
DEBUG:docker.auth.auth:No config file found
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.22/containers/json?all=0&limit=-1&trunc_cmd=0&size=0 HTTP/1.1" 200 None
INFO:werkzeug:172.17.0.2 - - [16/Nov/2016 16:44:39] "GET /api/v1/projects HTTP/1.1" 200 -
DEBUG:docker.auth.auth:Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
DEBUG:docker.auth.auth:No config file found
DEBUG:root:ps Azertypremierleague
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/json?all=1&limit=-1&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3DAzertypremierleague%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&size=0 HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/98e7f6e5d70b546ac73f4ce1c06a6247512d6c6759ac8276a0a3a6d6b8f80c1d/json HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/3e66c25378e40824577bb2193772520c75d3c1ee54a5b72b9e44ca3ab8de284a/json HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/5da35c64b70c0b2005b959edc8040003a1b50c55ed99ac6e1ef19db6b5cbe277/json HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/98e7f6e5d70b546ac73f4ce1c06a6247512d6c6759ac8276a0a3a6d6b8f80c1d/json HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/3e66c25378e40824577bb2193772520c75d3c1ee54a5b72b9e44ca3ab8de284a/json HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/5da35c64b70c0b2005b959edc8040003a1b50c55ed99ac6e1ef19db6b5cbe277/json HTTP/1.1" 200 None
INFO:werkzeug:172.17.0.2 - - [16/Nov/2016 16:44:39] "GET /api/v1/projects/Azerty%20Premier%20League HTTP/1.1" 200 -`

**Comment by allamand** [comment] 2016-11-16 19:19
I've got no idea :( have you tried without space in The project name ?

Sébastien

**Comment by francescou** [comment] 2016-11-16 20:15
Hi @abipit it was a bug caused by the non-lowercase project identifier, it should be fixed in d2fadad

thank you both for contributing

**Closed as completed by francescou** 2016-11-16 20:15 UTC

**Comment by abipit** [comment] 2016-11-16 20:57
Hi @francescou, thank you for your fix. In fact the lowercase was a problem.
I also remark that the "space" in the project name don't change the button on "ON".

Example now :
- project-name : OK
- Project-Name : now OK with your fix
- Project Name : KO

Can you also fix it please ? Is it possible ?
Thank you

**Comment by francescou** [comment] 2016-11-16 21:24
Hi, in 802dc48 I've implemented the same project id normalization used in docker-compose:  https://github.com/docker/compose/blob/1.9.0/compose/cli/command.py#L119

**Comment by abipit** [comment] 2016-11-16 22:21
It's perfect !! Thanks a lot @francescou
