### ISSUE TITLE
custom docker compose registry

### ISSUE THREAD

**Issue by bergtwvd** [francescou/docker-compose-ui#64] opened 2016-11-08 18:10 UTC
Currently the compose search engine is fixed to https://www.composeregistry.com.
Could this be may configurable?

**Comment by francescou** [comment] 2016-11-09 09:43
Hi, there is no option to configure the docker-compose registry at the moment.
The problem is that there isn't a "standard" API, so you should implement an API like this: https://www.composeregistry.com/documentation 

However...I plan to release the docker compose registry source code soon (I am the maintainer of Compose Registry), so it will be possible to have a self hosted instance. Then I will add an option to configure the registry URL in docker-compose-ui.

**Comment by bergtwvd** [comment] 2016-11-09 21:58
That would actually be great. Thanks.

**Comment by francescou** [comment] 2016-12-06 21:24
Hi @bergtwvd I've been working on a registry to be released as open source in the next days.

would you like to help me testing it? thanks

**Comment by bergtwvd** [comment] 2016-12-07 00:08
Yes, sure, no problem. Just send me the info.

**Comment by francescou** [comment] 2016-12-07 06:58
please send me an email so that I can add you as contributor

**Comment by bergtwvd** [comment] 2016-12-07 08:22
My GitHub accountname is bergtwvd.
Email address is on the cc.

**Comment by MichaelMackus** [comment] 2017-05-11 21:37
@francescou any update(s) on this? I'd be OK with just a configuration option to set the registry URL. Then, I can just implement the API endpoints I need in a custom app.

**Comment by francescou** [comment] 2017-05-14 17:35
Hi @MichaelMackus 
I didn't release the registry (yet) due to lack of time to work on it (I've made some tests with the help of @bergtwvd but I would like to improve the documentation before releasing it).
I would really appreciate it If you could contribute to the project.

Meanwhile, I've created an experimental branch: [custom-registry](https://github.com/francescou/docker-compose-ui/tree/custom-registry) to customize the docker-compose registry URL (you just have to add a `DOCKER_COMPOSE_REGISTRY` env). The feature is not finished yet but it should work.

**Comment by MichaelMackus** [comment] 2017-05-15 16:20
:+1: 

That looks like exactly what I need for my use case. I'll check it out and let you know how it works.

**Comment by francescou** [comment] 2017-08-25 12:15
Hello @bergtwvd and @MichaelMackus 
I've created a basic docker compose registry implementation: https://github.com/francescou/compose-registry and a swagger specification: https://raw.githubusercontent.com/francescou/compose-registry/master/api/swagger.yaml

Instructions:

```
docker run --rm \
  --name compose-registry \
  --volume $(pwd)/demo-projects/:/projects/:ro \
  --publish 8080:8080  \
  --read-only \
  francescou/compose-registry:0.2
```

```
docker pull francescou/docker-compose-ui
```

```
docker run --name docker-compose-ui \
  -p 5000:5000 \
  -e DOCKER_COMPOSE_REGISTRY=http://my-compose-registry:8080 \
  --link compose-registry:my-compose-registry \
  -w /opt/docker-compose-projects/ \
  -v /var/run/docker.sock:/var/run/docker.sock \
  francescou/docker-compose-ui
```

you can customize the current nodejs registry implementation of create a new one using another language/framework from the swagger specification following this documentation: https://github.com/francescou/compose-registry

Any feedback is welcome.

**Comment by almereyda** [comment] 2017-10-24 01:58
www.composeregistry.com is long down and parked at GoDaddy. This issue could be renamed to *custom compose registry* or alike.

**Closed as completed** 2020-11-18 03:48 UTC
