### ISSUE TITLE
Can't start my project

### ISSUE THREAD

**Issue by enko** [francescou/docker-compose-ui#57] opened 2016-11-01 10:27 UTC
I have created a demo project, which I cant up:

https://code.flyacts.com/tsc/docker-compose-example

npm complains that it cant find the `package.json` which is right because the volume `.:/usr/src/app` does not seem to be mounted?!?

If I start the project from a shell via `docker-compose up` it starts as expected.

**Comment by francescou** [comment] 2016-11-01 13:01
Hi, I guess the issue is caused by the relative path `.:/usr/src/app`

you could use workarounds discussed in #6 #49 and #50

**Comment by enko** [comment] 2016-11-01 14:48
I tried setting `${PWD}` instead of `.`, but this does not work. I'm getting this exception:

```
ERROR: for api  Cannot create container for service api: create .: "." includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed
Traceback (most recent call last):
  File "/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/scripts/requires_auth.py", line 54, in decorated
    return func(*args, **kwargs)
  File "/app/main.py", line 197, in up_
    do_build=do_build)
  File "/env/lib/python2.7/site-packages/compose/project.py", line 404, in up
    'Encountered errors while bringing up the project.'
ProjectError
```

The compose file looks like this:

``` yaml
version: "2"
services:
  api:
    build: .
    command: "npm -s start"
    environment:
      - NODE_ENV=development
    volumes:
        - ${PWD}:/usr/src/app
```

**Comment by francescou** [comment] 2016-11-03 12:30
you'll have to override the `PWD` env, e.g.

`docker  run --name docker-compose-ui -p 5000:5000 -e PWD=/projects/ -v /projects/:/opt/docker-compose-projects/ -v /var/run/docker.sock:/var/run/docker.sock  francescou/docker-compose-ui`

**Comment by francescou** [comment] 2016-11-09 10:43
Hi @enko did you solve the issue?

**Comment by francescou** [comment] 2016-11-16 20:21
I am closing the issue for now, feel free to reopen if necessary

**Closed as completed by francescou** 2016-11-16 20:21 UTC

**Comment by enko** [comment] 2016-11-17 08:34
Sorry to answer so late. I create an env file via CI which sets PWD which does everything right.
