### ISSUE TITLE
Add an option to define environment variable

### ISSUE THREAD

**Issue by liyaka** [francescou/docker-compose-ui#63] opened 2016-11-08 11:36 UTC
My Use case:
I use compose file with several environmental variable (like $VERSION, $BASE_PATH for volumes mapping and etc.). I deploy everything with ansible and save a text file with variables that were used for last deploy.
When I try to run scale on a service, compose-ui fails because env vars are not defined.
It would be nice to have an option to load env vars file from the same folder where compose file is and edit it (for the case you want to update a version and restart)

**Comment by allamand** [comment] 2016-11-08 17:27
Hi @liyaka I think it's a duplicate of #31

**Comment by francescou** [comment] 2016-11-09 09:47
Hi @liyaka if I understand you correctly it seems a duplicate of #31, so I'm closing the issue for now.
Feel free to reopen if necessary.

**Closed as completed by francescou** 2016-11-09 09:47 UTC
